short_name = "Rex"
name = "ReX Engine"
major = 0
minor = 1
patch = 0
status = "beta"
status_version = 0
module_config = ""
website = "https://redotengine.org"
docs = "latest"
redot_major = 0
redot_minor = 1
redot_patch = 0
redot_status = "dev"
